# -*- coding: utf-8 -*-
"""SQL-basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5XaZSUqbw-6AzPcBVjmOykP27ivb1jY
"""

# Commented out IPython magic to ensure Python compatibility.
# SQLをColabで使うための拡張機能
# %load_ext sql
##データの検索と絞りこみ
##条件の検索と絞り込み
#SELECT 取り出す列
#FROM どのテーブル
#WEHRE 条件
#ORDER BY どう並べるか　DESC(or ASC)
#LIMIT 何件


##グループ化
#SELECT グループ化する列　,SUM(計算する列）
#FROM どのテーブル
#GROUP BY グループ化する列
#HAVING 集計結果に対する条件


##データの結合
#SELECT テーブルA.取り出す列, テーブルB.取り出す列
#FROM テーブルA（ベース）
#JOIN テーブルB（くっつけるテーブル）　ON テーブルA.共通の列＝テーブルB.共通の列
#左外部結合
#SELECT テーブルA.取り出す列, テーブルB.取り出す列
#FROM テーブルA（ベース）
#LEFT JOIN テーブルB（くっつけるテーブル）　ON テーブルA.共通の列＝テーブルB.共通の列


##データに条件つきのラベルをつける
#SELECT 取り出す列,
    #CASE
	    #WHEN 条件　THEN '条件に当てはまる場合の値'
		#ELSE '当てはまらない場合の値'
	#END AS 新しい列の名前
#FROM テーブルの名前;

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql
SELECT
    users.user_id,
    users.user_name,
    SUM(investments.amount_jpy) AS total_investment,
    CASE
        WHEN SUM(investments.amount_jpy) >= 100000 THEN 'VIP'
        WHEN SUM(investments.amount_jpy) >= 1 THEN 'Standard'
        ELSE 'Newbie'
    END AS user_tier
FROM users
LEFT JOIN investments ON users.user_id = investments.user_id
GROUP BY users.user_id, users.user_name
ORDER BY total_investment DESC;

##COUNT関数とCOALESCE関数の練習
SELECT users.user_name,
    COUNT(investments.user_id) AS 'transaction_count',
    COALESCE(SUM(investments.amount_jpy),0) AS 'total_investments'
FROM users
LEFT JOIN investments ON users.user_id = investments.user_id
GROUP BY users.user_id, users.user_name;